### ISSUE TITLE
Error during make on Debian arm

### ISSUE THREAD

**Issue by Tassleh0ff** [yrutschle/conf2struct#11]
Hi, I have some problems during conf2struct setup, I installed all dependencies but during make I got this error

> root@banana:/usr/src# dpkg -l | grep libconfig8-dev
**ii  libconfig8-dev                         1.4.9-2                              armhf        Transitional package for libconfig-dev**
root@banana:/usr/src#
root@banana:/usr/src# cpan Conf::Libconfig
Reading '/root/.cpan/Metadata'
  Database was generated on Fri, 26 Jul 2019 11:41:02 GMT
**Conf::Libconfig is up to date (0.100).**
root@banana:/usr/src#
root@banana:/usr/src# cat /etc/debian_version ; uname -a
**8.11
Linux banana 3.4.113-bananian #9 SMP PREEMPT Sat May 6 12:20:11 UTC 2017 armv7l** GNU/Linux
root@banana:/usr/src#
root@banana:/usr/src# git clone https://github.com/yrutschle/conf2struct.git
Cloning into 'conf2struct'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 201 (delta 27), reused 34 (delta 14), pack-reused 148
Ricezione degli oggetti: 100% (201/201), 101.87 KiB | 0 bytes/s, done.
Risoluzione dei delta: 100% (116/116), done.
Checking connectivity... fatto.
root@banana:/usr/src#
root@banana:/usr/src# export LANG=en_EN.UTF-8
root@banana:/usr/src# cd conf2struct/
root@banana:/usr/src/conf2struct# make
**./conf2struct eg_conf.cfg
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_EN.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Use of uninitialized value in concatenation (.) or string at ./conf2struct line 1155.
Use of uninitialized value in concatenation (.) or string at ./conf2struct line 1155.
cc -g   -c -o example.o example.c
example.c: In function 'read_block':
example.c:750:15: warning: assignment makes pointer from integer without a cast
         if (s = config_setting_lookup(cfg, e->name)) {
               ^
example.c:756:17: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
                 for (int i = 0; i < len; i++) {
                 ^
example.c:756:17: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
example.c: In function 'eg_application_fprint':
example.c:1093:18: error: redeclaration of 'i' with no linkage
         for (int i = 0; i < eg_application->books_len; i++) {
                  ^
example.c:1085:13: note: previous declaration of 'i' was here
         int i;
             ^
example.c:1093:9: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
         for (int i = 0; i < eg_application->books_len; i++) {
         ^
<builtin>: recipe for target 'example.o' failed
make: *** [example.o] Error 1**

I changed LANG env variable to have an english output but I got the same errore using my default LANG (it_IT.UTF-8).

Does anyone have suggestions?

Thanks

**Comment by yrutschle** [comment]
Yes -- development of conf2struct is in flux and I am not sure what state the github head is in (I know, that's bad on my part, I should only check in working stuff...). 

The next issue you'll have is this one: https://github.com/yrutschle/sslh/issues/230 so I'd suggest trying to checkout that version directly. I can't guarantee it'll work, I haven't tried it.

I'm getting (slowly) closer to where I want to take conf2struct, and then I'll improve sslh build so it clones an appropriate version by itself.

**Comment by yrutschle** [comment]
This should work now, including sslh build with current v1.0 version of conf2struct.
